name: CNC-mode test
on: [push]
jobs:
  cnc-mode-test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up emacs
      uses: purcell/setup-emacs@v6.0
      with:
        version: 29.1
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Run ERT test suite
      run: emacs -batch -l ert -l cnc-mode.el -l cnc-mode-test.el -f ert-run-tests-batch-and-exit
